#pragma once
#include "types.h"

namespace zkp {

// Verifies a proof generated by generate_ecdsa_merkle_proof(...)
bool verify_ecdsa_merkle_proof(const Proof& proof, const PublicInputs& pub);

} // namespace zkp